### PR TITLE
[app-gdplay] - fix exit app

### PR DESCRIPTION
**Pull request by ManiacVera**
+ fix exit app

### CODE REVIEW

**Comment by ManiacVera** [comment]
Before the change it would freeze or show an error, I already checked it 10 times and so far everything is fine.

**Comment by DC-SWAT** [comment]
Hmm strange. This thd_join exists in UnloadApp: https://github.com/DC-SWAT/DreamShell/blob/master/src/app/load.c#L337

**Comment by ManiacVera** [comment]
I see it, yes, it's strange because if I don't put the thd_join I get an error the first or second time I exit the application.

So I'm going to put prints there to see if for some reason it doesn't go through that part, I don't know.

**Comment by ManiacVera** [comment]
See, in this function you use thd_join.

void gdplay_play(GUI_Widget *widget)
{
	(void) widget;

	self.kill_gdrom_thd = 1;
	thd_join(self.app->thd, NULL);

	ShutdownDS();
    arch_shutdown();

	gdplay_run_game(self.bios_patch);
}

**Comment by ManiacVera** [comment]
I'm going to delete it because if it is reaching the thd_join the strange thing is that putting it before avoids the error :D

**Comment by DC-SWAT** [comment]
> I'm going to delete it because if it is reaching the thd_join the strange thing is that putting it before avoids the error :D

Probably this issue appeared after I switched texture sending in video rendering to DMA. Because of this, some kind of race condition appeared...
OK, thanks you for pointing me!

**Pull request closed without merging**
